### PR TITLE
1.11.2 Client Crash

### PR DESCRIPTION
**Pull request by Zabofel**
Good evening, on our server began to receive an error: https://pastebin.com/Kam3u1Z9
Looking for possible reasons, I got such results: https://pastebin.com/F5p4ZAaZ
I got this result by owerride the method BlockRendererDispatcher#renderBlock(IBlockState,BlockPos,IBlockAccess,VertexBuffer): https://pastebin.com/99PRdWKR

Method Block#getExtendedState(state, blockAccess, pos) result null.

Sorry for my English.

### CODE REVIEW

**Comment by KingLemming** [comment]
You apparently opened a PR and not an issue. Please don't do that. :/

Also, this is not caused by us, due to this line:

at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:95)

They are hooking the rendering and passing us a bad value.

**Comment by Zabofel** [comment]
Bad state initializing in BlockRendererDispatcher, line state = state.getBlock().getExtendedState(state, blockAccess, pos); This return value has null.

**Comment by Zabofel** [comment]
I deleted BetterFoliage. [Crash Report](https://pastebin.com/DwL6wDhJ)

P.S. 
> You apparently opened a PR and not an issue. Please don't do that. :/

Excuse me, I did not find a way to open issue.

**Comment by KingLemming** [comment]
Please report it to CodeChicken. It's out of our hands.

**Comment by Zabofel** [comment]
Oh, https://github.com/TheCBProject/CodeChickenLib/issues/59

Okay, go BlockMachine#getExtendedState modified this method:

```
	public IBlockState getExtendedState(IBlockState state, IBlockAccess world, BlockPos pos) 
	{
		IBlockState extendedState = ModelBakery.handleExtendedState((IExtendedBlockState) super.getExtendedState(state, world, pos), world, pos);

		Objects.requireNonNull(extendedState);

		return extendedState;
	}
```

We get:

> java.lang.NullPointerException: Tesselating block in world
	at java.util.Objects.requireNonNull(Objects.java:203)
	at cofh.thermalexpansion.block.machine.BlockMachine.getExtendedState(BlockMachine.java:255)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:79)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:60)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:296)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:748)

**Pull request closed without merging**
