### PR TITLE
Wireless charging augment

### PR DESCRIPTION
**Pull request by Knugel**
Hey,
I hope it is ok to submit a feature suggestion as a PR.
This PR adds a new augment for the Energetic Infuser called Flux Field Exciter.
* Disables the normal charging mechanism.
* Charges capacitors in the players inventory as long as they are in range.
* Speed is 25% of the Flux Linkage Concentrator

### CODE REVIEW

**Comment by KingLemming** [comment]
You know, it's funny - I had originally written something like this maybe two months or so ago (when I wrote the repair augment) and then threw it out because I just didn't like the concept. I guess I was thinking it'd be more appropriate as a device?

But now I'm actually sort of coming around to it. Looks good. I'm gonna pull down a copy locally and test before I merge though. :)

**Comment by Leowbattle** [comment]
I think it would be a good idea to have it be able to have an adjustable range. This would be more expensive because it would passively consume RF, or maybe use more than you actually receive.

This wouldn't work with an augment though, because you can't have augment augments (unless you added a slider to the Energetic Infuser interface when the augment is installed).

This also wouldn't work as a device because they don't use RF.

So maybe it could be a machine. If it doesn't go against your rules about simplicity it could be crafted with an Energetic Infuser instead of a machine frame.

**Comment by KingLemming** [comment]
Why would it passively consume RF with an adjustable range?

It is entirely possible to add a range selector as well with the augment.

You're correct that devices don't use RF to perform their function, but if that function is literally just sending RF wirelessly to other things, that would be acceptable. The code isn't so inflexible that I can't do that.

**Comment by KingLemming** [comment]
Something that may be worth considering is that instead of AABB bounding boxes, you could iterate the player list and grab players within a certain euclidean distance.

I think that may actually be more performant (as the AABB check technically grabs ALL entities and then filters the desired one) as well as spherical.

Just shooting from the hip here, and that's a change I'd probably think about making anyways. Just putting it up here for feedback.

**Comment by Leowbattle** [comment]
I agree that that is a better idea. It would make a spherical detection area which seems more realistic.

When you say it is a change you would consider making, do you mean there are other parts of Thermal Expansion using AABB checks?

**Comment by KingLemming** [comment]
Nah, I just mean if I were to pull it. There are parts of TE using AABB checks, but they actually make more sense in those contexts.

This is just one of those things where given the typical number of players on the server vs entities in a given area, the spherical check might be faster. I'd have to see.

**Comment by Knugel** [comment]
I changed the augment to now use `World#playerEntities` instead of the AABB. 

As for using a machine/device, I think that the augment fits into the mod better especially considering that repairing isn't it's own machine either.
Also, is being able to decrease the range something that would be useful / commonly used?

**Comment by Leowbattle** [comment]
Maybe the range could depend on the tier of Energetic Infuser. So maybe a hardened one could reach 10 blocks, reinforced could reach 15, so on.

**Comment by Knugel** [comment]
It already does. The ranges currently are 3,5,7,9,11

**Comment by KingLemming** [comment]
I'm not sure the range changing with tier is really necessary since the power transfer already does.

**Comment by KingLemming** [comment]
@ImbaKnugel - Do you have a psd or pdn file for the augment? And would you have any way to get it to me?

**Comment by Knugel** [comment]
No, sorry. What do you need it for?

**Comment by KingLemming** [comment]
Well basically I'd like to tinker with the design of it. Maybe subtle things like changing the background or color.

**Comment by Knugel** [comment]
I only have a .png file. I just copied and modified the Flux Linkage Concentrator texture.

**Comment by KingLemming** [comment]
Gave it some thought. I constructed a .pdn file manually. I just like having them around as it's easy to adjust augments that way.

Looks good and I like it. :) Thanks for the contribution!

**Comment by KingLemming** [comment]
While I remember, @ImbaKnugel - do you have a twitter account? I'd like to properly credit you in as many channels as possible.

**Pull request merged**
