### PR TITLE
Patch for StackCrafting

### PR DESCRIPTION
**Pull request by Speiger**
Mini Patch to fix stackcrafting.

-Fixed: StackCrafting is now accounted for in the Item Collection.
-Fixed: StackCrafting is now accounted for when items are inserted into the crafting matrix.

### CODE REVIEW

**Comment by KingLemming** [comment]
Think there might be a small logic error. But this is a good template. Looking into it. :)

**Comment by Speiger** [comment]
Would be interesting to hear what logic error could be. 
Maybe I though of it? Maybe I missed it?
Also good that the quality is good enough :3

**Comment by KingLemming** [comment]
Line 694. The check there is to ensure that the total number of items committed is not more than the total available (> 0), but your new check is vs the items in a given stacksize, which is not technically correct.

**Comment by Speiger** [comment]
Yeah, I see what you mean.
Technically there is a potential with stackcrafting items to get into a "I am stuck scenario",
Yet stackcrafting (at least in ic2c) respects max stacksize of items.
But outside of that it is technically the same logic as before. Just >= instead of > 0.
But I get the point and agree that that should/could be changed/fixed?
Though that would blow the "its a simple fix scope"

**Comment by KingLemming** [comment]
There are a couple of other places where the right numbers aren't being added; the line right below for example.

Also, are you using custom ingredients for your stackcrafting? If you aren't, you really *should* be, otherwise the default Ingredient apply() effectively means that the recipe lies, and that's the only way I could see this being "stuck" offhand.

**Comment by Speiger** [comment]
I don't follow right now with the default Inredient (apply).
Could you elaborate that a bit more please?

**Comment by KingLemming** [comment]
Are you using a custom ingredient? If you are not, then the ingredient does not check stacksize. You can instead use a custom one to check for it.

**Comment by Speiger** [comment]
No I do not have a custom ingredient. That is not nessesary. It would even break your assembler because you actually do not consume the stacksize when checking if there is enough items.
So a custom ingredient makes not much sense since its ment only for "is the item the one you want?"
the checkRecipe function inside IRecipe should do the stacksize testing.

Another note: That would cause a bug where if you had 5 single items but you needed 5 items and the custom ingredient would not allow the custom collection method if wanted. Which is used by the way in ic2cs industrial workbench too where it craft needed extra items.

So your suggestion is a double edge sword and the current implementation works fine with any other autocrafter. (Because they usually dont use ingredients anyways and use the template that was provided anyways)

**Comment by KingLemming** [comment]
I agree. In fact the *reason* I don't check the stacksize is that Minecraft's implementation of Ingredient implicitly assumes that the stacksize is only one. That's why your use of it is improper - you should have a custom Ingredient that enforces the proper size up front.

I'll have to adjust code on my end either way, but it's not good practice for your recipe to say "yes but actually no" when checking validity, which is what it's doing now.

**Comment by KingLemming** [comment]
I've cobbled together something in dev now for this. :) Thanks.

**Comment by Speiger** [comment]
No Problem, and thanks for working on this issue.

**Pull request closed without merging**
